"""add_ratings

Revision ID: 901a72a4b7db
Revises: 5351476ff060
Create Date: 2022-11-06 19:39:27.033636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901a72a4b7db'
down_revision = '5351476ff060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('ratings', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passenger_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('ratings', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passenger_ratings')
    op.drop_table('driver_ratings')
    # ### end Alembic commands ###
