"""add_trip_id_to_report

Revision ID: bbe7b1a288a7
Revises: ecf93ffcc23c
Create Date: 2022-11-13 20:35:41.218321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe7b1a288a7'
down_revision = 'ecf93ffcc23c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_reports', sa.Column('trip_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_reports', 'trip_id')
    # ### end Alembic commands ###
