"""add driver state

Revision ID: beebfbe0a542
Revises: 5351476ff060
Create Date: 2022-10-15 17:27:09.979878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beebfbe0a542'
down_revision = '5351476ff060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'state')
    # ### end Alembic commands ###
