"""add_reports

Revision ID: ecf93ffcc23c
Revises: 901a72a4b7db
Create Date: 2022-11-07 01:14:41.534532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf93ffcc23c'
down_revision = '901a72a4b7db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_email', sa.String(length=50), nullable=False),
    sa.Column('passenger_email', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_reports')
    # ### end Alembic commands ###
