name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build containers
        run: docker-compose -f docker-compose.test.yml build
      - name: Run containers
        run: docker-compose -f docker-compose.test.yml up -d
      - name: Print ls
        run: docker-compose -f docker-compose.test.yml exec -T users_backend bash -c ls
      - name: Run tests
        run: docker-compose -f docker-compose.test.yml exec -T users_backend bash ./root/run_tests.sh
