name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # - name: Build containers
      #   run: docker-compose -f docker-compose.test.yml build
      # - name: Run containers
      #   run: docker-compose -f docker-compose.test.yml up -d
      # - name: Run tests
      #   run: docker-compose -f docker-compose.test.yml exec --exit-code-from users_backend -T users_backend bash ./run_tests.sh
      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.test.yml
          service: users_backend
          command: run_tests.sh
